# dont use wildcard imports because they make it unclear which functions are being used
# from users.actions import *
# from taxes.actions import pay_taxes

# this is an implementation of packages
# a package is a folder with an __init__.py file
from users.taxes.utilities import pay_taxes
import users
# another good way is:
# from users import actions
# then use actions.save()

# if we have sub packages we can do:
# from users.actions import utilities
# then use utilities.save()
# or
# from users.actions.utilities import save
# then use save()

# print(dir(users))
print(dir(users.__name__))
print(dir(users.__package__))
print(dir(users.__path__))
print(dir(users.__file__))

# save()
# pay_taxes()

# for modules file names use conventional naming like user.py
# and for multiple words use underscores like user_profile.py

# folder is created autogenerated __pycache__/
# it contains compiled versions of the modules to make loading faster
# file name structure is <module_name>.cpython-<version>.pyc
